rvm: '2.0.0'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g bower
  - bower install

script:
  - bundle exec bin/rake db:create
  - bundle exec bin/rake db:migrate
  - bundle exec rspec spec

addons:
  code_climate:
    repo_token: 896771448094978736170a6d017cd97203b3bd08e970935cb3e1f615db68f0b8